name: containerd
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["containerd/**"]
permissions:
  contents: read
  packages: write
defaults:
  run:
    shell: bash
jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Get versions
        id: versions
        run: |
          versions=$(cat containerd/versions.yaml | yq '.versions | tojson')
          echo "versions=$versions" >> $GITHUB_OUTPUT
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #v4.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f #v7.1.0
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: ./containerd
          build-args: CONTAINERD_VERSION=${{ matrix.version }}
          platforms: linux/amd64
          tags: ghcr.io/spegel-org/test-images/containerd:${{ matrix.version }}
