name: containerd
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["containerd/**"]
permissions:
  contents: read
  packages: write
defaults:
  run:
    shell: bash
jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - name: Clone repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - name: Get versions
        id: versions
        run: |
          versions=$(yq '.versions' containerd/versions.yaml -o json | jq -c '.')
          echo "versions=$versions" >> $GITHUB_OUTPUT
  release:
    needs: versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.versions.outputs.versions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 #v4.1.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee #v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf #v7.2.0
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: ./containerd
          build-args: CONTAINERD_VERSION=${{ matrix.version }}
          platforms: linux/amd64
          tags: ghcr.io/spegel-org/test-images/containerd:${{ matrix.version }}
          sbom: false
          provenance: false
