name: kind
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["kind/**"]
permissions:
  contents: read
  packages: write
defaults:
  run:
    shell: bash
jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Get versions
        id: versions
        run: |
          versions=$(yq '.versions' kind/versions.yaml -o json | jq -c '.')
          echo "versions=$versions" >> $GITHUB_OUTPUT
  release:
    needs: versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.versions.outputs.versions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Kind
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc #v1.14.0
        with:
          version: v0.31.0
          install_only: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build kind node image
        run: |
          kind build node-image --image ghcr.io/spegel-org/test-images/kind-node:${{ matrix.version }} ${{ matrix.version }}
          docker push ghcr.io/spegel-org/test-images/kind-node:${{ matrix.version }}
